export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

export const RETRIEVE_ROLE_SUCCESS = "RETRIEVE_ROLE_SUCCESS";
export const RETRIEVE_ROLE_FAIL = "RETRIEVE_ROLE_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const CREATE_AGAMA_SUCCESS = "CREATE_AGAMA_SUCCESS";
export const CREATE_AGAMA_FAIL = "CREATE_AGAMA_FAIL";
export const RETRIEVE_AGAMA_SUCCESS = "RETRIEVE_AGAMA_SUCCESS";
export const RETRIEVE_AGAMA_FAIL = "RETRIEVE_AGAMA_FAIL";
export const RESET_AGAMA_SUCCESS = "RESET_AGAMA_SUCCESS";
export const UPDATE_AGAMA_SUCCESS = "UPDATE_AGAMA_SUCCESS";
export const UPDATE_AGAMA_FAIL = "UPDATE_AGAMA_FAIL";
export const DELETE_AGAMA_SUCCESS = "DELETE_AGAMA_SUCCESS";
export const DELETE_AGAMA_FAIL = "DELETE_AGAMA_FAIL";

export const CREATE_BANK_SUCCESS = "CREATE_BANK_SUCCESS";
export const CREATE_BANK_FAIL = "CREATE_BANK_FAIL";
export const RETRIEVE_BANK_SUCCESS = "RETRIEVE_BANK_SUCCESS";
export const RETRIEVE_BANK_FAIL = "RETRIEVE_BANK_FAIL";
export const RESET_BANK_SUCCESS = "RESET_BANK_SUCCESS";
export const UPDATE_BANK_SUCCESS = "UPDATE_BANK_SUCCESS";
export const UPDATE_BANK_FAIL = "UPDATE_BANK_FAIL";
export const DELETE_BANK_SUCCESS = "DELETE_BANK_SUCCESS";
export const DELETE_BANK_FAIL = "DELETE_BANK_FAIL";

export const CREATE_BASEMAP_SUCCESS = "CREATE_BASEMAP_SUCCESS";
export const CREATE_BASEMAP_FAIL = "CREATE_BASEMAP_FAIL";
export const RETRIEVE_BASEMAP_SUCCESS = "RETRIEVE_BASEMAP_SUCCESS";
export const RETRIEVE_BASEMAP_FAIL = "RETRIEVE_BASEMAP_FAIL";
export const RESET_BASEMAP_SUCCESS = "RESET_BASEMAP_SUCCESS";
export const UPDATE_BASEMAP_SUCCESS = "UPDATE_BASEMAP_SUCCESS";
export const UPDATE_BASEMAP_FAIL = "UPDATE_BASEMAP_FAIL";
export const DELETE_BASEMAP_SUCCESS = "DELETE_BASEMAP_SUCCESS";
export const DELETE_BASEMAP_FAIL = "DELETE_BASEMAP_FAIL";

export const CREATE_KANTOR_SUCCESS = "CREATE_KANTOR_SUCCESS";
export const CREATE_KANTOR_FAIL = "CREATE_KANTOR_FAIL";
export const RETRIEVE_KANTOR_SUCCESS = "RETRIEVE_KANTOR_SUCCESS";
export const RETRIEVE_KANTOR_FAIL = "RETRIEVE_KANTOR_FAIL";
export const RESET_KANTOR_SUCCESS = "RESET_KANTOR_SUCCESS";
export const UPDATE_KANTOR_SUCCESS = "UPDATE_KANTOR_SUCCESS";
export const UPDATE_KANTOR_FAIL = "UPDATE_KANTOR_FAIL";
export const DELETE_KANTOR_SUCCESS = "DELETE_KANTOR_SUCCESS";
export const DELETE_KANTOR_FAIL = "DELETE_KANTOR_FAIL";

export const CREATE_ORGANISASI_SUCCESS = "CREATE_ORGANISASI_SUCCESS";
export const CREATE_ORGANISASI_FAIL = "CREATE_ORGANISASI_FAIL";
export const RETRIEVE_ORGANISASI_SUCCESS = "RETRIEVE_ORGANISASI_SUCCESS";
export const RETRIEVE_ORGANISASI_FAIL = "RETRIEVE_ORGANISASI_FAIL";
export const RESET_ORGANISASI_SUCCESS = "RESET_ORGANISASI_SUCCESS";
export const UPDATE_ORGANISASI_SUCCESS = "UPDATE_ORGANISASI_SUCCESS";
export const UPDATE_ORGANISASI_FAIL = "UPDATE_ORGANISASI_FAIL";
export const DELETE_ORGANISASI_SUCCESS = "DELETE_ORGANISASI_SUCCESS";
export const DELETE_ORGANISASI_FAIL = "DELETE_ORGANISASI_FAIL";

export const CREATE_PANGKAT_SUCCESS = "CREATE_PANGKAT_SUCCESS";
export const CREATE_PANGKAT_FAIL = "CREATE_PANGKAT_FAIL";
export const RETRIEVE_PANGKAT_SUCCESS = "RETRIEVE_PANGKAT_SUCCESS";
export const RETRIEVE_PANGKAT_FAIL = "RETRIEVE_PANGKAT_FAIL";
export const RESET_PANGKAT_SUCCESS = "RESET_PANGKAT_SUCCESS";
export const UPDATE_PANGKAT_SUCCESS = "UPDATE_PANGKAT_SUCCESS";
export const UPDATE_PANGKAT_FAIL = "UPDATE_PANGKAT_FAIL";
export const DELETE_PANGKAT_SUCCESS = "DELETE_PANGKAT_SUCCESS";
export const DELETE_PANGKAT_FAIL = "DELETE_PANGKAT_FAIL";

export const CREATE_JENIS_CUTI_SUCCESS = "CREATE_JENIS_CUTI_SUCCESS";
export const CREATE_JENIS_CUTI_FAIL = "CREATE_JENIS_CUTI_FAIL";
export const RETRIEVE_JENIS_CUTI_SUCCESS = "RETRIEVE_JENIS_CUTI_SUCCESS";
export const RETRIEVE_JENIS_CUTI_FAIL = "RETRIEVE_JENIS_CUTI_FAIL";
export const RESET_JENIS_CUTI_SUCCESS = "RESET_JENIS_CUTI_SUCCESS";
export const UPDATE_JENIS_CUTI_SUCCESS = "UPDATE_JENIS_CUTI_SUCCESS";
export const UPDATE_JENIS_CUTI_FAIL = "UPDATE_JENIS_CUTI_FAIL";
export const DELETE_JENIS_CUTI_SUCCESS = "DELETE_JENIS_CUTI_SUCCESS";
export const DELETE_JENIS_CUTI_FAIL = "DELETE_JENIS_CUTI_FAIL";

export const CREATE_JENIS_AKTIFITAS_SUCCESS = "CREATE_JENIS_AKTIFITAS_SUCCESS";
export const CREATE_JENIS_AKTIFITAS_FAIL = "CREATE_JENIS_AKTIFITAS_FAIL";
export const RETRIEVE_JENIS_AKTIFITAS_SUCCESS =
  "RETRIEVE_JENIS_AKTIFITAS_SUCCESS";
export const RETRIEVE_JENIS_AKTIFITAS_FAIL = "RETRIEVE_JENIS_AKTIFITAS_FAIL";
export const RESET_JENIS_AKTIFITAS_SUCCESS = "RESET_JENIS_AKTIFITAS_SUCCESS";
export const UPDATE_JENIS_AKTIFITAS_SUCCESS = "UPDATE_JENIS_AKTIFITAS_SUCCESS";
export const UPDATE_JENIS_AKTIFITAS_FAIL = "UPDATE_JENIS_AKTIFITAS_FAIL";
export const DELETE_JENIS_AKTIFITAS_SUCCESS = "DELETE_JENIS_AKTIFITAS_SUCCESS";
export const DELETE_JENIS_AKTIFITAS_FAIL = "DELETE_JENIS_AKTIFITAS_FAIL";

export const CREATE_TIPE_JABATAN_SUCCESS = "CREATE_TIPE_JABATAN_SUCCESS";
export const CREATE_TIPE_JABATAN_FAIL = "CREATE_TIPE_JABATAN_FAIL";
export const RETRIEVE_TIPE_JABATAN_SUCCESS = "RETRIEVE_TIPE_JABATAN_SUCCESS";
export const RETRIEVE_TIPE_JABATAN_FAIL = "RETRIEVE_TIPE_JABATAN_FAIL";
export const RESET_TIPE_JABATAN_SUCCESS = "RESET_TIPE_JABATAN_SUCCESS";
export const UPDATE_TIPE_JABATAN_SUCCESS = "UPDATE_TIPE_JABATAN_SUCCESS";
export const UPDATE_TIPE_JABATAN_FAIL = "UPDATE_TIPE_JABATAN_FAIL";
export const DELETE_TIPE_JABATAN_SUCCESS = "DELETE_TIPE_JABATAN_SUCCESS";
export const DELETE_TIPE_JABATAN_FAIL = "DELETE_TIPE_JABATAN_FAIL";

export const CREATE_JENIS_KELAMIN_SUCCESS = "CREATE_JENIS_KELAMIN_SUCCESS";
export const CREATE_JENIS_KELAMIN_FAIL = "CREATE_JENIS_KELAMIN_FAIL";
export const RETRIEVE_JENIS_KELAMIN_SUCCESS = "RETRIEVE_JENIS_KELAMIN_SUCCESS";
export const RETRIEVE_JENIS_KELAMIN_FAIL = "RETRIEVE_JENIS_KELAMIN_FAIL";
export const RESET_JENIS_KELAMIN_SUCCESS = "RESET_JENIS_KELAMIN_SUCCESS";
export const UPDATE_JENIS_KELAMIN_SUCCESS = "UPDATE_JENIS_KELAMIN_SUCCESS";
export const UPDATE_JENIS_KELAMIN_FAIL = "UPDATE_JENIS_KELAMIN_FAIL";
export const DELETE_JENIS_KELAMIN_SUCCESS = "DELETE_JENIS_KELAMIN_SUCCESS";
export const DELETE_JENIS_KELAMIN_FAIL = "DELETE_JENIS_KELAMIN_FAIL";

export const CREATE_JENIS_JABATAN_SUCCESS = "CREATE_JENIS_JABATAN_SUCCESS";
export const CREATE_JENIS_JABATAN_FAIL = "CREATE_JENIS_JABATAN_FAIL";
export const RETRIEVE_JENIS_JABATAN_SUCCESS = "RETRIEVE_JENIS_JABATAN_SUCCESS";
export const RETRIEVE_JENIS_JABATAN_FAIL = "RETRIEVE_JENIS_JABATAN_FAIL";
export const RESET_JENIS_JABATAN_SUCCESS = "RESET_JENIS_JABATAN_SUCCESS";
export const UPDATE_JENIS_JABATAN_SUCCESS = "UPDATE_JENIS_JABATAN_SUCCESS";
export const UPDATE_JENIS_JABATAN_FAIL = "UPDATE_JENIS_JABATAN_FAIL";
export const DELETE_JENIS_JABATAN_SUCCESS = "DELETE_JENIS_JABATAN_SUCCESS";
export const DELETE_JENIS_JABATAN_FAIL = "DELETE_JENIS_JABATAN_FAIL";

export const CREATE_JENIS_ALAT_ANGKUT_SUCCESS =
  "CREATE_JENIS_ALAT_ANGKUT_SUCCESS";
export const CREATE_JENIS_ALAT_ANGKUT_FAIL = "CREATE_JENIS_ALAT_ANGKUT_FAIL";
export const RETRIEVE_JENIS_ALAT_ANGKUT_SUCCESS =
  "RETRIEVE_JENIS_ALAT_ANGKUT_SUCCESS";
export const RETRIEVE_JENIS_ALAT_ANGKUT_FAIL =
  "RETRIEVE_JENIS_ALAT_ANGKUT_FAIL";
export const RESET_JENIS_ALAT_ANGKUT_SUCCESS =
  "RESET_JENIS_ALAT_ANGKUT_SUCCESS";
export const UPDATE_JENIS_ALAT_ANGKUT_SUCCESS =
  "UPDATE_JENIS_ALAT_ANGKUT_SUCCESS";
export const UPDATE_JENIS_ALAT_ANGKUT_FAIL = "UPDATE_JENIS_ALAT_ANGKUT_FAIL";
export const DELETE_JENIS_ALAT_ANGKUT_SUCCESS =
  "DELETE_JENIS_ALAT_ANGKUT_SUCCESS";
export const DELETE_JENIS_ALAT_ANGKUT_FAIL = "DELETE_JENIS_ALAT_ANGKUT_FAIL";

export const CREATE_GEDUNG_SUCCESS = "CREATE_GEDUNG_SUCCESS";
export const CREATE_GEDUNG_FAIL = "CREATE_GEDUNG_FAIL";
export const RETRIEVE_GEDUNG_SUCCESS = "RETRIEVE_GEDUNG_SUCCESS";
export const RETRIEVE_GEDUNG_FAIL = "RETRIEVE_GEDUNG_FAIL";
export const RESET_GEDUNG_SUCCESS = "RESET_GEDUNG_SUCCESS";
export const UPDATE_GEDUNG_SUCCESS = "UPDATE_GEDUNG_SUCCESS";
export const UPDATE_GEDUNG_FAIL = "UPDATE_GEDUNG_FAIL";
export const DELETE_GEDUNG_SUCCESS = "DELETE_GEDUNG_SUCCESS";
export const DELETE_GEDUNG_FAIL = "DELETE_GEDUNG_FAIL";

export const CREATE_GOLONGAN_DARAH_SUCCESS = "CREATE_GOLONGAN_DARAH_SUCCESS";
export const CREATE_GOLONGAN_DARAH_FAIL = "CREATE_GOLONGAN_DARAH_FAIL";
export const RETRIEVE_GOLONGAN_DARAH_SUCCESS =
  "RETRIEVE_GOLONGAN_DARAH_SUCCESS";
export const RETRIEVE_GOLONGAN_DARAH_FAIL = "RETRIEVE_GOLONGAN_DARAH_FAIL";
export const RESET_GOLONGAN_DARAH_SUCCESS = "RESET_GOLONGAN_DARAH_SUCCESS";
export const UPDATE_GOLONGAN_DARAH_SUCCESS = "UPDATE_GOLONGAN_DARAH_SUCCESS";
export const UPDATE_GOLONGAN_DARAH_FAIL = "UPDATE_GOLONGAN_DARAH_FAIL";
export const DELETE_GOLONGAN_DARAH_SUCCESS = "DELETE_GOLONGAN_DARAH_SUCCESS";
export const DELETE_GOLONGAN_DARAH_FAIL = "DELETE_GOLONGAN_DARAH_FAIL";

export const CREATE_HARI_LIBUR_SUCCESS = "CREATE_HARI_LIBUR_SUCCESS";
export const CREATE_HARI_LIBUR_FAIL = "CREATE_HARI_LIBUR_FAIL";
export const RETRIEVE_HARI_LIBUR_SUCCESS = "RETRIEVE_HARI_LIBUR_SUCCESS";
export const RETRIEVE_HARI_LIBUR_FAIL = "RETRIEVE_HARI_LIBUR_FAIL";
export const RESET_HARI_LIBUR_SUCCESS = "RESET_HARI_LIBUR_SUCCESS";
export const UPDATE_HARI_LIBUR_SUCCESS = "UPDATE_HARI_LIBUR_SUCCESS";
export const UPDATE_HARI_LIBUR_FAIL = "UPDATE_HARI_LIBUR_FAIL";
export const DELETE_HARI_LIBUR_SUCCESS = "DELETE_HARI_LIBUR_SUCCESS";
export const DELETE_HARI_LIBUR_FAIL = "DELETE_HARI_LIBUR_FAIL";

export const CREATE_JENIS_KP_SUCCESS = "CREATE_JENIS_KP_SUCCESS";
export const CREATE_JENIS_KP_FAIL = "CREATE_JENIS_KP_FAIL";
export const RETRIEVE_JENIS_KP_SUCCESS = "RETRIEVE_JENIS_KP_SUCCESS";
export const RETRIEVE_JENIS_KP_FAIL = "RETRIEVE_JENIS_KP_FAIL";
export const RESET_JENIS_KP_SUCCESS = "RESET_JENIS_KP_SUCCESS";
export const UPDATE_JENIS_KP_SUCCESS = "UPDATE_JENIS_KP_SUCCESS";
export const UPDATE_JENIS_KP_FAIL = "UPDATE_JENIS_KP_FAIL";
export const DELETE_JENIS_KP_SUCCESS = "DELETE_JENIS_KP_SUCCESS";
export const DELETE_JENIS_KP_FAIL = "DELETE_JENIS_KP_FAIL";

export const CREATE_JENIS_OS_SUCCESS = "CREATE_JENIS_OS_SUCCESS";
export const CREATE_JENIS_OS_FAIL = "CREATE_JENIS_OS_FAIL";
export const RETRIEVE_JENIS_OS_SUCCESS = "RETRIEVE_JENIS_OS_SUCCESS";
export const RETRIEVE_JENIS_OS_FAIL = "RETRIEVE_JENIS_OS_FAIL";
export const RESET_JENIS_OS_SUCCESS = "RESET_JENIS_OS_SUCCESS";
export const UPDATE_JENIS_OS_SUCCESS = "UPDATE_JENIS_OS_SUCCESS";
export const UPDATE_JENIS_OS_FAIL = "UPDATE_JENIS_OS_FAIL";
export const DELETE_JENIS_OS_SUCCESS = "DELETE_JENIS_OS_SUCCESS";
export const DELETE_JENIS_OS_FAIL = "DELETE_JENIS_OS_FAIL";

export const CREATE_JENIS_PENSIUN_SUCCESS = "CREATE_JENIS_PENSIUN_SUCCESS";
export const CREATE_JENIS_PENSIUN_FAIL = "CREATE_JENIS_PENSIUN_FAIL";
export const RETRIEVE_JENIS_PENSIUN_SUCCESS = "RETRIEVE_JENIS_PENSIUN_SUCCESS";
export const RETRIEVE_JENIS_PENSIUN_FAIL = "RETRIEVE_JENIS_PENSIUN_FAIL";
export const RESET_JENIS_PENSIUN_SUCCESS = "RESET_JENIS_PENSIUN_SUCCESS";
export const UPDATE_JENIS_PENSIUN_SUCCESS = "UPDATE_JENIS_PENSIUN_SUCCESS";
export const UPDATE_JENIS_PENSIUN_FAIL = "UPDATE_JENIS_PENSIUN_FAIL";
export const DELETE_JENIS_PENSIUN_SUCCESS = "DELETE_JENIS_PENSIUN_SUCCESS";
export const DELETE_JENIS_PENSIUN_FAIL = "DELETE_JENIS_PENSIUN_FAIL";

export const CREATE_JENIS_TRANSPORT_PERJADIN_SUCCESS =
  "CREATE_JENIS_TRANSPORT_PERJADIN_SUCCESS";
export const CREATE_JENIS_TRANSPORT_PERJADIN_FAIL =
  "CREATE_JENIS_TRANSPORT_PERJADIN_FAIL";
export const RETRIEVE_JENIS_TRANSPORT_PERJADIN_SUCCESS =
  "RETRIEVE_JENIS_TRANSPORT_PERJADIN_SUCCESS";
export const RETRIEVE_JENIS_TRANSPORT_PERJADIN_FAIL =
  "RETRIEVE_JENIS_TRANSPORT_PERJADIN_FAIL";
export const RESET_JENIS_TRANSPORT_PERJADIN_SUCCESS =
  "RESET_JENIS_TRANSPORT_PERJADIN_SUCCESS";
export const UPDATE_JENIS_TRANSPORT_PERJADIN_SUCCESS =
  "UPDATE_JENIS_TRANSPORT_PERJADIN_SUCCESS";
export const UPDATE_JENIS_TRANSPORT_PERJADIN_FAIL =
  "UPDATE_JENIS_TRANSPORT_PERJADIN_FAIL";
export const DELETE_JENIS_TRANSPORT_PERJADIN_SUCCESS =
  "DELETE_JENIS_TRANSPORT_PERJADIN_SUCCESS";
export const DELETE_JENIS_TRANSPORT_PERJADIN_FAIL =
  "DELETE_JENIS_TRANSPORT_PERJADIN_FAIL";

export const CREATE_KATEGORI_PROPORSI_SUCCESS =
  "CREATE_KATEGORI_PROPORSI_SUCCESS";
export const CREATE_KATEGORI_PROPORSI_FAIL = "CREATE_KATEGORI_PROPORSI_FAIL";
export const RETRIEVE_KATEGORI_PROPORSI_SUCCESS =
  "RETRIEVE_KATEGORI_PROPORSI_SUCCESS";
export const RETRIEVE_KATEGORI_PROPORSI_FAIL =
  "RETRIEVE_KATEGORI_PROPORSI_FAIL";
export const RESET_KATEGORI_PROPORSI_SUCCESS =
  "RESET_KATEGORI_PROPORSI_SUCCESS";
export const UPDATE_KATEGORI_PROPORSI_SUCCESS =
  "UPDATE_KATEGORI_PROPORSI_SUCCESS";
export const UPDATE_KATEGORI_PROPORSI_FAIL = "UPDATE_KATEGORI_PROPORSI_FAIL";
export const DELETE_KATEGORI_PROPORSI_SUCCESS =
  "DELETE_KATEGORI_PROPORSI_SUCCESS";
export const DELETE_KATEGORI_PROPORSI_FAIL = "DELETE_KATEGORI_PROPORSI_FAIL";

export const CREATE_KEDUDUKAN_PEGAWAI_SUCCESS =
  "CREATE_KEDUDUKAN_PEGAWAI_SUCCESS";
export const CREATE_KEDUDUKAN_PEGAWAI_FAIL = "CREATE_KEDUDUKAN_PEGAWAI_FAIL";
export const RETRIEVE_KEDUDUKAN_PEGAWAI_SUCCESS =
  "RETRIEVE_KEDUDUKAN_PEGAWAI_SUCCESS";
export const RETRIEVE_KEDUDUKAN_PEGAWAI_FAIL =
  "RETRIEVE_KEDUDUKAN_PEGAWAI_FAIL";
export const RESET_KEDUDUKAN_PEGAWAI_SUCCESS =
  "RESET_KEDUDUKAN_PEGAWAI_SUCCESS";
export const UPDATE_KEDUDUKAN_PEGAWAI_SUCCESS =
  "UPDATE_KEDUDUKAN_PEGAWAI_SUCCESS";
export const UPDATE_KEDUDUKAN_PEGAWAI_FAIL = "UPDATE_KEDUDUKAN_PEGAWAI_FAIL";
export const DELETE_KEDUDUKAN_PEGAWAI_SUCCESS =
  "DELETE_KEDUDUKAN_PEGAWAI_SUCCESS";
export const DELETE_KEDUDUKAN_PEGAWAI_FAIL = "DELETE_KEDUDUKAN_PEGAWAI_FAIL";

export const CREATE_KELAS_TUNKIN_SUCCESS = "CREATE_KELAS_TUNKIN_SUCCESS";
export const CREATE_KELAS_TUNKIN_FAIL = "CREATE_KELAS_TUNKIN_FAIL";
export const RETRIEVE_KELAS_TUNKIN_SUCCESS = "RETRIEVE_KELAS_TUNKIN_SUCCESS";
export const RETRIEVE_KELAS_TUNKIN_FAIL = "RETRIEVE_KELAS_TUNKIN_FAIL";
export const RESET_KELAS_TUNKIN_SUCCESS = "RESET_KELAS_TUNKIN_SUCCESS";
export const UPDATE_KELAS_TUNKIN_SUCCESS = "UPDATE_KELAS_TUNKIN_SUCCESS";
export const UPDATE_KELAS_TUNKIN_FAIL = "UPDATE_KELAS_TUNKIN_FAIL";
export const DELETE_KELAS_TUNKIN_SUCCESS = "DELETE_KELAS_TUNKIN_SUCCESS";
export const DELETE_KELAS_TUNKIN_FAIL = "DELETE_KELAS_TUNKIN_FAIL";

export const CREATE_LEVEL_WILAYAH_SUCCESS = "CREATE_LEVEL_WILAYAH_SUCCESS";
export const CREATE_LEVEL_WILAYAH_FAIL = "CREATE_LEVEL_WILAYAH_FAIL";
export const RETRIEVE_LEVEL_WILAYAH_SUCCESS = "RETRIEVE_LEVEL_WILAYAH_SUCCESS";
export const RETRIEVE_LEVEL_WILAYAH_FAIL = "RETRIEVE_LEVEL_WILAYAH_FAIL";
export const RESET_LEVEL_WILAYAH_SUCCESS = "RESET_LEVEL_WILAYAH_SUCCESS";
export const UPDATE_LEVEL_WILAYAH_SUCCESS = "UPDATE_LEVEL_WILAYAH_SUCCESS";
export const UPDATE_LEVEL_WILAYAH_FAIL = "UPDATE_LEVEL_WILAYAH_FAIL";
export const DELETE_LEVEL_WILAYAH_SUCCESS = "DELETE_LEVEL_WILAYAH_SUCCESS";
export const DELETE_LEVEL_WILAYAH_FAIL = "DELETE_LEVEL_WILAYAH_FAIL";

export const CREATE_PENDIDIKAN_SUCCESS = "CREATE_PENDIDIKAN_SUCCESS";
export const CREATE_PENDIDIKAN_FAIL = "CREATE_PENDIDIKAN_FAIL";
export const RETRIEVE_PENDIDIKAN_SUCCESS = "RETRIEVE_PENDIDIKAN_SUCCESS";
export const RETRIEVE_PENDIDIKAN_FAIL = "RETRIEVE_PENDIDIKAN_FAIL";
export const RESET_PENDIDIKAN_SUCCESS = "RESET_PENDIDIKAN_SUCCESS";
export const UPDATE_PENDIDIKAN_SUCCESS = "UPDATE_PENDIDIKAN_SUCCESS";
export const UPDATE_PENDIDIKAN_FAIL = "UPDATE_PENDIDIKAN_FAIL";
export const DELETE_PENDIDIKAN_SUCCESS = "DELETE_PENDIDIKAN_SUCCESS";
export const DELETE_PENDIDIKAN_FAIL = "DELETE_PENDIDIKAN_FAIL";

export const CREATE_POLA_KERJA_SUCCESS = "CREATE_POLA_KERJA_SUCCESS";
export const CREATE_POLA_KERJA_FAIL = "CREATE_POLA_KERJA_FAIL";
export const RETRIEVE_POLA_KERJA_SUCCESS = "RETRIEVE_POLA_KERJA_SUCCESS";
export const RETRIEVE_POLA_KERJA_FAIL = "RETRIEVE_POLA_KERJA_FAIL";
export const RESET_POLA_KERJA_SUCCESS = "RESET_POLA_KERJA_SUCCESS";
export const UPDATE_POLA_KERJA_SUCCESS = "UPDATE_POLA_KERJA_SUCCESS";
export const UPDATE_POLA_KERJA_FAIL = "UPDATE_POLA_KERJA_FAIL";
export const DELETE_POLA_KERJA_SUCCESS = "DELETE_POLA_KERJA_SUCCESS";
export const DELETE_POLA_KERJA_FAIL = "DELETE_POLA_KERJA_FAIL";

export const CREATE_STATUS_KEHADIRAN_SUCCESS =
  "CREATE_STATUS_KEHADIRAN_SUCCESS";
export const CREATE_STATUS_KEHADIRAN_FAIL = "CREATE_STATUS_KEHADIRAN_FAIL";
export const RETRIEVE_STATUS_KEHADIRAN_SUCCESS =
  "RETRIEVE_STATUS_KEHADIRAN_SUCCESS";
export const RETRIEVE_STATUS_KEHADIRAN_FAIL = "RETRIEVE_STATUS_KEHADIRAN_FAIL";
export const RESET_STATUS_KEHADIRAN_SUCCESS = "RESET_STATUS_KEHADIRAN_SUCCESS";
export const UPDATE_STATUS_KEHADIRAN_SUCCESS =
  "UPDATE_STATUS_KEHADIRAN_SUCCESS";
export const UPDATE_STATUS_KEHADIRAN_FAIL = "UPDATE_STATUS_KEHADIRAN_FAIL";
export const DELETE_STATUS_KEHADIRAN_SUCCESS =
  "DELETE_STATUS_KEHADIRAN_SUCCESS";
export const DELETE_STATUS_KEHADIRAN_FAIL = "DELETE_STATUS_KEHADIRAN_FAIL";

export const CREATE_STATUS_PEGAWAI_SUCCESS = "CREATE_STATUS_PEGAWAI_SUCCESS";
export const CREATE_STATUS_PEGAWAI_FAIL = "CREATE_STATUS_PEGAWAI_FAIL";
export const RETRIEVE_STATUS_PEGAWAI_SUCCESS =
  "RETRIEVE_STATUS_PEGAWAI_SUCCESS";
export const RETRIEVE_STATUS_PEGAWAI_FAIL = "RETRIEVE_STATUS_PEGAWAI_FAIL";
export const RESET_STATUS_PEGAWAI_SUCCESS = "RESET_STATUS_PEGAWAI_SUCCESS";
export const UPDATE_STATUS_PEGAWAI_SUCCESS = "UPDATE_STATUS_PEGAWAI_SUCCESS";
export const UPDATE_STATUS_PEGAWAI_FAIL = "UPDATE_STATUS_PEGAWAI_FAIL";
export const DELETE_STATUS_PEGAWAI_SUCCESS = "DELETE_STATUS_PEGAWAI_SUCCESS";
export const DELETE_STATUS_PEGAWAI_FAIL = "DELETE_STATUS_PEGAWAI_FAIL";

export const CREATE_STATUS_PERKAWINAN_SUCCESS =
  "CREATE_STATUS_PERKAWINAN_SUCCESS";
export const CREATE_STATUS_PERKAWINAN_FAIL = "CREATE_STATUS_PERKAWINAN_FAIL";
export const RETRIEVE_STATUS_PERKAWINAN_SUCCESS =
  "RETRIEVE_STATUS_PERKAWINAN_SUCCESS";
export const RETRIEVE_STATUS_PERKAWINAN_FAIL =
  "RETRIEVE_STATUS_PERKAWINAN_FAIL";
export const RESET_STATUS_PERKAWINAN_SUCCESS =
  "RESET_STATUS_PERKAWINAN_SUCCESS";
export const UPDATE_STATUS_PERKAWINAN_SUCCESS =
  "UPDATE_STATUS_PERKAWINAN_SUCCESS";
export const UPDATE_STATUS_PERKAWINAN_FAIL = "UPDATE_STATUS_PERKAWINAN_FAIL";
export const DELETE_STATUS_PERKAWINAN_SUCCESS =
  "DELETE_STATUS_PERKAWINAN_SUCCESS";
export const DELETE_STATUS_PERKAWINAN_FAIL = "DELETE_STATUS_PERKAWINAN_FAIL";

export const CREATE_STATUS_PERSETUJUAN_SUCCESS =
  "CREATE_STATUS_PERSETUJUAN_SUCCESS";
export const CREATE_STATUS_PERSETUJUAN_FAIL = "CREATE_STATUS_PERSETUJUAN_FAIL";
export const RETRIEVE_STATUS_PERSETUJUAN_SUCCESS =
  "RETRIEVE_STATUS_PERSETUJUAN_SUCCESS";
export const RETRIEVE_STATUS_PERSETUJUAN_FAIL =
  "RETRIEVE_STATUS_PERSETUJUAN_FAIL";
export const RESET_STATUS_PERSETUJUAN_SUCCESS =
  "RESET_STATUS_PERSETUJUAN_SUCCESS";
export const UPDATE_STATUS_PERSETUJUAN_SUCCESS =
  "UPDATE_STATUS_PERSETUJUAN_SUCCESS";
export const UPDATE_STATUS_PERSETUJUAN_FAIL = "UPDATE_STATUS_PERSETUJUAN_FAIL";
export const DELETE_STATUS_PERSETUJUAN_SUCCESS =
  "DELETE_STATUS_PERSETUJUAN_SUCCESS";
export const DELETE_STATUS_PERSETUJUAN_FAIL = "DELETE_STATUS_PERSETUJUAN_FAIL";

export const CREATE_TINGKAT_BIAYA_PERJADIN_SUCCESS =
  "CREATE_TINGKAT_BIAYA_PERJADIN_SUCCESS";
export const CREATE_TINGKAT_BIAYA_PERJADIN_FAIL =
  "CREATE_TINGKAT_BIAYA_PERJADIN_FAIL";
export const RETRIEVE_TINGKAT_BIAYA_PERJADIN_SUCCESS =
  "RETRIEVE_TINGKAT_BIAYA_PERJADIN_SUCCESS";
export const RETRIEVE_TINGKAT_BIAYA_PERJADIN_FAIL =
  "RETRIEVE_TINGKAT_BIAYA_PERJADIN_FAIL";
export const RESET_TINGKAT_BIAYA_PERJADIN_SUCCESS =
  "RESET_TINGKAT_BIAYA_PERJADIN_SUCCESS";
export const UPDATE_TINGKAT_BIAYA_PERJADIN_SUCCESS =
  "UPDATE_TINGKAT_BIAYA_PERJADIN_SUCCESS";
export const UPDATE_TINGKAT_BIAYA_PERJADIN_FAIL =
  "UPDATE_TINGKAT_BIAYA_PERJADIN_FAIL";
export const DELETE_TINGKAT_BIAYA_PERJADIN_SUCCESS =
  "DELETE_TINGKAT_BIAYA_PERJADIN_SUCCESS";
export const DELETE_TINGKAT_BIAYA_PERJADIN_FAIL =
  "DELETE_TINGKAT_BIAYA_PERJADIN_FAIL";

export const CREATE_TUJUAN_PERJADIN_SUCCESS = "CREATE_TUJUAN_PERJADIN_SUCCESS";
export const CREATE_TUJUAN_PERJADIN_FAIL = "CREATE_TUJUAN_PERJADIN_FAIL";
export const RETRIEVE_TUJUAN_PERJADIN_SUCCESS =
  "RETRIEVE_TUJUAN_PERJADIN_SUCCESS";
export const RETRIEVE_TUJUAN_PERJADIN_FAIL = "RETRIEVE_TUJUAN_PERJADIN_FAIL";
export const RESET_TUJUAN_PERJADIN_SUCCESS = "RESET_TUJUAN_PERJADIN_SUCCESS";
export const UPDATE_TUJUAN_PERJADIN_SUCCESS = "UPDATE_TUJUAN_PERJADIN_SUCCESS";
export const UPDATE_TUJUAN_PERJADIN_FAIL = "UPDATE_TUJUAN_PERJADIN_FAIL";
export const DELETE_TUJUAN_PERJADIN_SUCCESS = "DELETE_TUJUAN_PERJADIN_SUCCESS";
export const DELETE_TUJUAN_PERJADIN_FAIL = "DELETE_TUJUAN_PERJADIN_FAIL";

export const CREATE_WILAYAH_SUCCESS = "CREATE_WILAYAH_SUCCESS";
export const CREATE_WILAYAH_FAIL = "CREATE_WILAYAH_FAIL";
export const RETRIEVE_WILAYAH_SUCCESS = "RETRIEVE_WILAYAH_SUCCESS";
export const RETRIEVE_WILAYAH_FAIL = "RETRIEVE_WILAYAH_FAIL";
export const RESET_WILAYAH_SUCCESS = "RESET_WILAYAH_SUCCESS";
export const UPDATE_WILAYAH_SUCCESS = "UPDATE_WILAYAH_SUCCESS";
export const UPDATE_WILAYAH_FAIL = "UPDATE_WILAYAH_FAIL";
export const DELETE_WILAYAH_SUCCESS = "DELETE_WILAYAH_SUCCESS";
export const DELETE_WILAYAH_FAIL = "DELETE_WILAYAH_FAIL";

export const CREATE_PERANGKAT_SUCCESS = "CREATE_PERANGKAT_SUCCESS";
export const CREATE_PERANGKAT_FAIL = "CREATE_PERANGKAT_FAIL";
export const RETRIEVE_PERANGKAT_SUCCESS = "RETRIEVE_PERANGKAT_SUCCESS";
export const RETRIEVE_PERANGKAT_FAIL = "RETRIEVE_PERANGKAT_FAIL";
export const RESET_PERANGKAT_SUCCESS = "RESET_PERANGKAT_SUCCESS";
export const UPDATE_PERANGKAT_SUCCESS = "UPDATE_PERANGKAT_SUCCESS";
export const UPDATE_PERANGKAT_FAIL = "UPDATE_PERANGKAT_FAIL";
export const DELETE_PERANGKAT_SUCCESS = "DELETE_PERANGKAT_SUCCESS";
export const DELETE_PERANGKAT_FAIL = "DELETE_PERANGKAT_FAIL";

export const CREATE_JABATAN_SUCCESS = "CREATE_JABATAN_SUCCESS";
export const CREATE_JABATAN_FAIL = "CREATE_JABATAN_FAIL";
export const RETRIEVE_JABATAN_SUCCESS = "RETRIEVE_JABATAN_SUCCESS";
export const RETRIEVE_JABATAN_FAIL = "RETRIEVE_JABATAN_FAIL";
export const RESET_JABATAN_SUCCESS = "RESET_JABATAN_SUCCESS";
export const UPDATE_JABATAN_SUCCESS = "UPDATE_JABATAN_SUCCESS";
export const UPDATE_JABATAN_FAIL = "UPDATE_JABATAN_FAIL";
export const DELETE_JABATAN_SUCCESS = "DELETE_JABATAN_SUCCESS";
export const DELETE_JABATAN_FAIL = "DELETE_JABATAN_FAIL";

export const CREATE_PEGAWAI_SUCCESS = "CREATE_PEGAWAI_SUCCESS";
export const CREATE_PEGAWAI_FAIL = "CREATE_PEGAWAI_FAIL";
export const RETRIEVE_PEGAWAI_SUCCESS = "RETRIEVE_PEGAWAI_SUCCESS";
export const RETRIEVE_PEGAWAI_FAIL = "RETRIEVE_PEGAWAI_FAIL";
export const RESET_PEGAWAI_SUCCESS = "RESET_PEGAWAI_SUCCESS";
export const UPDATE_PEGAWAI_SUCCESS = "UPDATE_PEGAWAI_SUCCESS";
export const UPDATE_PEGAWAI_FAIL = "UPDATE_PEGAWAI_FAIL";
export const DELETE_PEGAWAI_SUCCESS = "DELETE_PEGAWAI_SUCCESS";
export const DELETE_PEGAWAI_FAIL = "DELETE_PEGAWAI_FAIL";

export const CREATE_RIWAYAT_PANGKAT_SUCCESS = "CREATE_RIWAYAT_PANGKAT_SUCCESS";
export const CREATE_RIWAYAT_PANGKAT_FAIL = "CREATE_RIWAYAT_PANGKAT_FAIL";
export const RETRIEVE_RIWAYAT_PANGKAT_SUCCESS = "RETRIEVE_RIWAYAT_PANGKAT_SUCCESS";
export const RETRIEVE_RIWAYAT_PANGKAT_FAIL = "RETRIEVE_RIWAYAT_PANGKAT_FAIL";
export const RESET_RIWAYAT_PANGKAT_SUCCESS = "RESET_RIWAYAT_PANGKAT_SUCCESS";
export const UPDATE_RIWAYAT_PANGKAT_SUCCESS = "UPDATE_RIWAYAT_PANGKAT_SUCCESS";
export const UPDATE_RIWAYAT_PANGKAT_FAIL = "UPDATE_RIWAYAT_PANGKAT_FAIL";
export const DELETE_RIWAYAT_PANGKAT_SUCCESS = "DELETE_RIWAYAT_PANGKAT_SUCCESS";
export const DELETE_RIWAYAT_PANGKAT_FAIL = "DELETE_RIWAYAT_PANGKAT_FAIL";

export const CREATE_RIWAYAT_JABATAN_SUCCESS = "CREATE_RIWAYAT_JABATAN_SUCCESS";
export const CREATE_RIWAYAT_JABATAN_FAIL = "CREATE_RIWAYAT_JABATAN_FAIL";
export const RETRIEVE_RIWAYAT_JABATAN_SUCCESS = "RETRIEVE_RIWAYAT_JABATAN_SUCCESS";
export const RETRIEVE_RIWAYAT_JABATAN_FAIL = "RETRIEVE_RIWAYAT_JABATAN_FAIL";
export const RESET_RIWAYAT_JABATAN_SUCCESS = "RESET_RIWAYAT_JABATAN_SUCCESS";
export const UPDATE_RIWAYAT_JABATAN_SUCCESS = "UPDATE_RIWAYAT_JABATAN_SUCCESS";
export const UPDATE_RIWAYAT_JABATAN_FAIL = "UPDATE_RIWAYAT_JABATAN_FAIL";
export const DELETE_RIWAYAT_JABATAN_SUCCESS = "DELETE_RIWAYAT_JABATAN_SUCCESS";
export const DELETE_RIWAYAT_JABATAN_FAIL = "DELETE_RIWAYAT_JABATAN_FAIL";

export const CREATE_RIWAYAT_SATMINKAL_SUCCESS = "CREATE_RIWAYAT_SATMINKAL_SUCCESS";
export const CREATE_RIWAYAT_SATMINKAL_FAIL = "CREATE_RIWAYAT_SATMINKAL_FAIL";
export const RETRIEVE_RIWAYAT_SATMINKAL_SUCCESS = "RETRIEVE_RIWAYAT_SATMINKAL_SUCCESS";
export const RETRIEVE_RIWAYAT_SATMINKAL_FAIL = "RETRIEVE_RIWAYAT_SATMINKAL_FAIL";
export const RESET_RIWAYAT_SATMINKAL_SUCCESS = "RESET_RIWAYAT_SATMINKAL_SUCCESS";
export const UPDATE_RIWAYAT_SATMINKAL_SUCCESS = "UPDATE_RIWAYAT_SATMINKAL_SUCCESS";
export const UPDATE_RIWAYAT_SATMINKAL_FAIL = "UPDATE_RIWAYAT_SATMINKAL_FAIL";
export const DELETE_RIWAYAT_SATMINKAL_SUCCESS = "DELETE_RIWAYAT_SATMINKAL_SUCCESS";
export const DELETE_RIWAYAT_SATMINKAL_FAIL = "DELETE_RIWAYAT_SATMINKAL_FAIL";

export const CREATE_RIWAYAT_TUBEL_SUCCESS = "CREATE_RIWAYAT_TUBEL_SUCCESS";
export const CREATE_RIWAYAT_TUBEL_FAIL = "CREATE_RIWAYAT_TUBEL_FAIL";
export const RETRIEVE_RIWAYAT_TUBEL_SUCCESS = "RETRIEVE_RIWAYAT_TUBEL_SUCCESS";
export const RETRIEVE_RIWAYAT_TUBEL_FAIL = "RETRIEVE_RIWAYAT_TUBEL_FAIL";
export const RESET_RIWAYAT_TUBEL_SUCCESS = "RESET_RIWAYAT_TUBEL_SUCCESS";
export const UPDATE_RIWAYAT_TUBEL_SUCCESS = "UPDATE_RIWAYAT_TUBEL_SUCCESS";
export const UPDATE_RIWAYAT_TUBEL_FAIL = "UPDATE_RIWAYAT_TUBEL_FAIL";
export const DELETE_RIWAYAT_TUBEL_SUCCESS = "DELETE_RIWAYAT_TUBEL_SUCCESS";
export const DELETE_RIWAYAT_TUBEL_FAIL = "DELETE_RIWAYAT_TUBEL_FAIL";
